openshift:
  enabled: true

appName: csc-rstudio-shiny

rstudio:
  podSecurityContext: {}
  containerSecurityContext:
    runAsUser:
    runAsGroup:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  pvc:
    mountName: rstudio-server-home
    storageSize: 5Gi

shiny:
  pvc:
    mountName: shiny-server
    storageSize: 5Gi

buildConfig:
  gitRepoUri: https://github.com/trispera/rstudio-shiny.git
  gitBranch: main

route:
  insecureEdgeTerminationPolicy: Redirect
  termination: edge
  host: ""